#!/bin/bash

source "$PWD"/shell/colors.sh
source "$PWD"/shell/ascii.sh

while read local_ref local_sha remote_ref remote_sha; do
    if [[ "$local_ref" =~ ^refs/heads/ ]]; then
        branch_name=$(echo "$local_ref" | sed 's|^refs/heads/||')

        if [[ ! "$branch_name" =~ ^(feature|fix|hotfix|docs|refactor|build|test|develop)/.*$ ]]; then
            echo "${bold}Branch names must start with 'feature/', 'fix/', 'refactor/', 'docs/', 'test/' or 'hotfix/' followed by a fancy description."
            exit 1
        fi
    fi
done

exit 0
